/* Copyright 2026 Advanced Micro Devices, Inc.
 * Copyright 2026 Valve Corporation
 * SPDX-License-Identifier: MIT
 */

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "common.h"
#include "extras/hash_table.h"

#define MIN_SIZE                 512
#define MAX_SIZE                 (256 * 1024 * 1024)

/* This divides the maximum size and execution time of host memory tests by this number
 * to compensate for very low PCIe throughput and limited usefulness with UMA.
 */
#define HOSTMEM_TEST_REDUCTION   16

/* Each column grows using this multiplier. It can be non-integer. */
#define SIZE_STEP_MUL            2

/* The typical size of all memory requests generated by each test. This determines the execution
 * time, though small sizes are also capped by MAX_RUNS.
 */
#define EXECUTION_SIZE     (512 * 1024 * 1024)
#define MAX_RUNS           4096

#define MAX_ALIGNMENT      (64 * 1024)

enum {
   TEST_FILL,
   TEST_COPY,
   TEST_COPY_INDIRECT,
   NUM_TESTS,
};

enum {
   HIT,
   MISS,
   MISS_NO_BARRIER,
   NUM_TRAVERSAL_TYPES,
};

enum {
   ALIGN_MAX,
   ALIGN_256,
   ALIGN_128,
   ALIGN_64,
   ALIGN_4,
   ALIGN_2,
   ALIGN_1,
   ALIGN_SRC256,
   ALIGN_SRC128,
   ALIGN_SRC64,
   ALIGN_SRC4,
   ALIGN_SRC2,
   ALIGN_SRC1,
   ALIGN_DST256,
   ALIGN_DST128,
   ALIGN_DST64,
   ALIGN_DST4,
   ALIGN_DST2,
   ALIGN_DST1,
   ALIGN_SRC4_DST2,
   ALIGN_SRC4_DST1,
   ALIGN_SRC2_DST4,
   ALIGN_SRC2_DST1,
   ALIGN_SRC1_DST4,
   ALIGN_SRC1_DST2,
   NUM_ALIGNMENTS,
};

struct align_info_t {
   const char *string;
   unsigned src_offset;
   unsigned dst_offset;
};

#define ALIGN_BOTH(value)        [ALIGN_##value] = {"both="#value, value, value}
#define ALIGN_SRC(src)           [ALIGN_SRC##src] = {"src="#src, src, 0}
#define ALIGN_DST(dst)           [ALIGN_DST##dst] = {"dst="#dst, 0, dst}
#define ALIGN_SRC_DST(src, dst)  [ALIGN_SRC##src##_DST##dst] = {"src="#src".dst="#dst, src, dst}

static const struct align_info_t align_info[] = {
   [ALIGN_MAX] = {"maxalign", 0, 0},
   ALIGN_BOTH(256),
   ALIGN_BOTH(128),
   ALIGN_BOTH(64),
   ALIGN_BOTH(4),
   ALIGN_BOTH(2),
   ALIGN_BOTH(1),
   ALIGN_SRC(256),
   ALIGN_SRC(128),
   ALIGN_SRC(64),
   ALIGN_SRC(4),
   ALIGN_SRC(2),
   ALIGN_SRC(1),
   ALIGN_DST(256),
   ALIGN_DST(128),
   ALIGN_DST(64),
   ALIGN_DST(4),
   ALIGN_DST(2),
   ALIGN_DST(1),
   ALIGN_SRC_DST(4, 2),
   ALIGN_SRC_DST(4, 1),
   ALIGN_SRC_DST(2, 4),
   ALIGN_SRC_DST(2, 1),
   ALIGN_SRC_DST(1, 4),
   ALIGN_SRC_DST(1, 2),
};

enum test_stage {
   COUNT_TESTS,
   RUN,
   REPORT,
};

typedef struct {
   uint64_t dst_address;
   uint64_t src_address;
   unsigned size;
} indirect_params;

static uint32_t
indirect_params_hash(const void *key)
{
   return fnv1a_hash(key, sizeof(indirect_params));
}

static bool
indirect_params_equal(const void *a, const void *b)
{
   return !memcmp(a, b, sizeof(indirect_params));
}

static void
param_info_entry_delete(struct hash_entry *entry)
{
   free((void*)entry->key);
   free(entry->data);
}

static unsigned
next_size(unsigned size)
{
   int order = logbase2(size) - 3;
   assert(order >= 2);

   return ALIGN_POT((unsigned)(size * SIZE_STEP_MUL), 1 << order);
}

typedef struct {
   unsigned num_tests;
   api_query_pool *timestamps;
   api_queue_type queue;
   api_buffer *devmem0;
   api_buffer *devmem1;
   api_buffer *hostmem;
   api_buffer *indirect;
   struct hash_table indirect_params_ht;
} test_state;

static void
run(api_context *ctx, enum test_stage stage, test_state *state)
{
   const unsigned name_indent = 70;

   if (stage == REPORT) {
      printf("%-*s", name_indent, "Allocation size");
      for (unsigned size = MIN_SIZE; size <= MAX_SIZE; size = next_size(size)) {
         if (size >= 4 * 1024 * 1024)
            printf(",%6uMB", size / (1024 * 1024));
         else if (size >= 4 * 1024)
            printf(",%6uKB", size / 1024);
         else
            printf(", %6uB", size);
      }
      printf("\n");
   }

   const bool has_indirect = ctx->queue_has_copy_memory_indirect[state->queue];
   const unsigned num_test_types = 2 + has_indirect;
   atomic_uint num_visited_tests = 0;

   /* Run tests. */
   for (unsigned test_type = 0; test_type < num_test_types; test_type++) {
      unsigned num_indirect_entries = _mesa_hash_table_num_entries(&state->indirect_params_ht);

      /* Upload the indirect buffer and set indirect buffer addresses in the hash table before
       * the first indirect test.
       */
      if (stage == RUN && test_type == TEST_COPY_INDIRECT && num_indirect_entries) {
         unsigned buf_size = num_indirect_entries * 24;
         uint64_t *indirect_data = malloc(buf_size);

         state->indirect = ctx->create_buffer(ctx, buf_size, api_heap_device, 0);

         unsigned i = 0;
         hash_table_foreach(&state->indirect_params_ht, entry) {
            const indirect_params *params = entry->key;

            indirect_data[i * 3 + 0] = params->src_address;
            indirect_data[i * 3 + 1] = params->dst_address;
            indirect_data[i * 3 + 2] = params->size;

            *(uint64_t*)entry->data = state->indirect->device_address + i * 24;
            i++;
         }

         ctx->upload_buffer_data(ctx, state->indirect, 0, buf_size, indirect_data);
         free(indirect_data);
      }

      bool is_copy = test_type != TEST_FILL;

      for (unsigned src_heap_index = 0; src_heap_index < (is_copy ? 2 : 1); src_heap_index++) {
         for (unsigned dst_heap_index = 0; dst_heap_index < 2; dst_heap_index++) {
            if (dst_heap_index == 1 && src_heap_index == 1)
               continue;

            api_buffer *dst = dst_heap_index == 0 ? state->devmem0 : state->hostmem;
            api_buffer *src = is_copy ? (src_heap_index == 0 ? state->devmem1 : state->hostmem) : NULL;

            assert(dst);
            assert(!src || src != dst);
            bool uses_hostmem = dst->heap != api_heap_device || (src && src->heap != api_heap_device);

            if (!ctx->has_heap[api_heap_host_uncached] && (dst == state->hostmem || src == state->hostmem))
               continue;

            for (unsigned traversal = 0; traversal < NUM_TRAVERSAL_TYPES; traversal++) {
               unsigned cycled_offset_base = 0;

               for (unsigned align = 0; align < NUM_ALIGNMENTS; align++) {
                  unsigned test_src_offset = align_info[align].src_offset;
                  unsigned test_dst_offset = align_info[align].dst_offset;

                  /* Instead of making offsets unaligned by some number from 0 (e.g. 1, 2, 3), make
                   * them unaligned by some number from 4 (e.g. 5, 6, 7).
                   */
                  if (test_src_offset && test_src_offset < 4)
                     test_src_offset += 4;
                  if (test_dst_offset && test_dst_offset < 4)
                     test_dst_offset += 4;

                  if (!is_copy && (test_src_offset != 0 || test_dst_offset % 4))
                     continue;

                  char subtest[512];
                  snprintf(subtest, sizeof(subtest), "%s.%s%s%s.%s.%s",
                           test_type == TEST_FILL ? "fill" :
                           test_type == TEST_COPY ? "copy" :
                           test_type == TEST_COPY_INDIRECT ? "copy_indirect" : "(error)",
                           is_copy ? heap_to_string(src->heap) : "",
                           is_copy ? "_to_" : "",
                           heap_to_string(dst->heap),
                           traversal == HIT ? "hit" :
                           traversal == MISS ? "miss" : "miss_no_barrier",
                           align_info[align].string);

                  if (ctx->options.regex_subtest_filter &&
                      !regex_matches(ctx->options.regex_subtest_filter, subtest))
                     continue;

                  if (stage == REPORT) {
                     char name[1024];
                     snprintf(name, sizeof(name), "%s.%s", ctx->options.name_prefix, subtest);
                     printf("%-*s", name_indent, name);
                  }

                  for (unsigned size = MIN_SIZE; size <= MAX_SIZE; size = next_size(size)) {
                     /* Don't test large sizes with host memory because it can be too slow. */
                     if ((size > MAX_SIZE / HOSTMEM_TEST_REDUCTION && uses_hostmem) ||
                         (traversal == MISS_NO_BARRIER && ctx->buffer_barrier_has_gl_semantics)) {
                        if (stage == REPORT)
                           printf(",%8s", "n/a");
                        continue;
                     }

                     if (stage == COUNT_TESTS)
                        state->num_tests++;

                     const unsigned execution_size = EXECUTION_SIZE / (uses_hostmem ? HOSTMEM_TEST_REDUCTION : 1);
                     const unsigned num_runs = MAX2(MIN2(execution_size / size, MAX_RUNS), 1);
                     const unsigned num_warmup_runs = MAX2(num_runs / 4, 1);

                     if (stage == RUN) {
                        ctx->begin_cmdbuf(ctx, state->queue);

                        for (unsigned iter = 0; iter < num_warmup_runs + num_runs; iter++) {
                           if (iter == num_warmup_runs)
                              ctx->write_next_query_value(ctx, state->timestamps);

                           if ((cycled_offset_base + test_dst_offset + size > dst->size) ||
                               (is_copy && cycled_offset_base + test_src_offset + size > src->size))
                              cycled_offset_base = 0;

                           assert(cycled_offset_base + test_dst_offset + size <= dst->size);
                           assert(!is_copy || cycled_offset_base + test_src_offset + size <= src->size);
                           assert(cycled_offset_base % MAX_ALIGNMENT == 0);

                           uint64_t dst_offset = cycled_offset_base + test_dst_offset;

                           if (is_copy) {
                              uint64_t src_offset = cycled_offset_base + test_src_offset;

                              indirect_params params = {
                                 .dst_address = dst->device_address + dst_offset,
                                 .src_address = src->device_address + src_offset,
                                 .size = size,
                              };

                              if (test_type == TEST_COPY_INDIRECT) {
                                 /* Look up the indirect buffer address from the hash table. */
                                 struct hash_entry *entry =
                                    _mesa_hash_table_search(&state->indirect_params_ht, &params);
                                 assert(entry);

                                 uint64_t indirect_address = *(uint64_t*)entry->data;
                                 assert(indirect_address);

                                 ctx->copy_memory_indirect(ctx, 1, indirect_address, 24,
                                                           dst->heap == api_heap_device ?
                                                              VK_ADDRESS_COPY_DEVICE_LOCAL_BIT_KHR : 0,
                                                           src->heap == api_heap_device ?
                                                              VK_ADDRESS_COPY_DEVICE_LOCAL_BIT_KHR : 0);
                              } else {
                                 ctx->copy_buffer(ctx, dst, src, dst_offset, src_offset, size);

                                 if (has_indirect) {
                                    /* Populate the hash table with entries.
                                     * The indirect buffer will be allocated and the hash table will
                                     * be populated with correct addresses before the first indirect test.
                                     */
                                    indirect_params *key = malloc(sizeof(params));
                                    uint64_t *address = malloc(sizeof(uint64_t));

                                    *key = params;
                                    *address = 0;

                                    _mesa_hash_table_insert(&state->indirect_params_ht, key, address);
                                 }
                              }

                              if (traversal != MISS_NO_BARRIER) {
                                 ctx->barrier_buffers(ctx, 2, (api_buffer*[2]){src, dst},
                                                      (uint64_t[]){src_offset, size, dst_offset, size}, false);
                              }
                           } else {
                              ctx->clear_buffer(ctx, dst, dst_offset, size, 0x23456789);

                              if (traversal != MISS_NO_BARRIER)
                                 ctx->barrier_buffers(ctx, 1, &dst, (uint64_t[]){dst_offset, size}, false);
                           }

                           if (traversal != HIT) {
                              /* Use a different portion of the buffers for each test, so that they don't just
                               * stay in the cache.
                               */
                              cycled_offset_base += size;
                              cycled_offset_base = ALIGN_POT(cycled_offset_base, MAX_ALIGNMENT);
                           }
                        }

                        ctx->write_next_query_value(ctx, state->timestamps);
                        ctx->end_cmdbuf_and_submit(ctx, 0, NULL, NULL);
                     }

                     if (stage == REPORT) {
                        /* When copying from DEVMEM to DEVMEM, we put 2x demand on DEVMEM bandwidth, and when
                         * copying between DEVMEM and HOSTMEM, we put only 1x demand on each, so only double
                         * the size for DEVMEM->DEVMEM copies to use the real DEVMEM bandwidth usage.
                         */
                        uint64_t num_bytes = (uint64_t)size * num_runs *
                                             (is_copy && dst_heap_index == src_heap_index ? 2 : 1);
                        print_throughput_from_next_timestamps(ctx, state->timestamps, num_bytes, NULL, "%8.2f", "%8s", 30);
                     }

                     if (stage == RUN)
                        print_progress(state->num_tests, &num_visited_tests, 20);
                  }

                  if (stage == REPORT)
                     puts("");
               }
            }
         }
      }
   }
}

void
test_bufbw(api_context *ctx)
{
   api_queue_type queue;

   if (ctx->options.compute)
      queue = api_queue_compute;
   else if (ctx->options.transfer)
      queue = api_queue_transfer;
   else
      queue = api_queue_gfx;

   if (!ctx->has_queue[queue])
      error("%s queue support is required.", queue_to_string(queue));

   printf("Using the %s queue.\n", queue_to_string(queue));

   test_state state = {0};

   /* Create buffers. */
   /* We allocate enough memory and cycle through the whole range to prevent caching. */
   unsigned buf_size = 2 * MAX_SIZE + 256;
   state.devmem0 = ctx->create_buffer(ctx, buf_size, api_heap_device, 0);
   state.devmem1 = ctx->create_buffer(ctx, buf_size, api_heap_device, 0);
   state.hostmem = ctx->create_buffer(ctx, buf_size, api_heap_host_uncached, 0);
   state.queue = queue;

   _mesa_hash_table_init(&state.indirect_params_ht, indirect_params_hash, indirect_params_equal);

   run(ctx, COUNT_TESTS, &state);

   /* Create timestamp queries. */
   state.timestamps = ctx->create_query_pool(ctx, state.num_tests * 2, api_query_timestamp);

   printf("Executing tests ...");
   fflush(stdout);
   run(ctx, RUN, &state);
   puts("");

   ctx->get_query_results(ctx, state.timestamps);

   puts("Units: GB/s");
   run(ctx, REPORT, &state);

   _mesa_hash_table_fini(&state.indirect_params_ht, param_info_entry_delete);
}
