/* Copyright 2026 Advanced Micro Devices, Inc.
 * SPDX-License-Identifier: MIT
 */

#include <assert.h>
#include <stdio.h>
#include <strings.h>

#include "common.h"

#define MIN_SIZE                 512
#define MAX_SIZE                 (256 * 1024 * 1024)

/* This divides the maximum size and execution time of host memory tests by this number
 * to compensate for very low PCIe throughput and limited usefulness with UMA.
 */
#define HOSTMEM_TEST_REDUCTION   16

/* Each column grows using this multiplier. It can be non-integer. */
#define SIZE_STEP_MUL            2

/* The typical size of all memory requests generated by each test. This determines the execution
 * time, though small sizes are also capped by MAX_RUNS.
 */
#define EXECUTION_SIZE     (512 * 1024 * 1024)
#define MAX_RUNS           4096

#define MAX_ALIGNMENT      (64 * 1024)

enum {
   TEST_FILL_DEVMEM,
   TEST_FILL_HOSTMEM,
   TEST_COPY_DEVMEM_TO_DEVMEM,
   TEST_COPY_DEVMEM_TO_HOSTMEM,
   TEST_COPY_HOSTMEM_TO_DEVMEM,
   NUM_TESTS,
};

static const char *test_strings[] = {
   [TEST_FILL_DEVMEM] = "fill.devmem",
   [TEST_FILL_HOSTMEM] = "fill.hostmem",
   [TEST_COPY_DEVMEM_TO_DEVMEM] = "copy.devmem_to_devmem",
   [TEST_COPY_DEVMEM_TO_HOSTMEM] = "copy.devmem_to_hostmem",
   [TEST_COPY_HOSTMEM_TO_DEVMEM] = "copy.hostmem_to_devmem",
};

enum {
   ALIGN_MAX,
   ALIGN_256,
   ALIGN_128,
   ALIGN_64,
   ALIGN_4,
   ALIGN_2,
   ALIGN_1,
   ALIGN_SRC256,
   ALIGN_SRC128,
   ALIGN_SRC64,
   ALIGN_SRC4,
   ALIGN_SRC2,
   ALIGN_SRC1,
   ALIGN_DST256,
   ALIGN_DST128,
   ALIGN_DST64,
   ALIGN_DST4,
   ALIGN_DST2,
   ALIGN_DST1,
   ALIGN_SRC4_DST2,
   ALIGN_SRC4_DST1,
   ALIGN_SRC2_DST4,
   ALIGN_SRC2_DST1,
   ALIGN_SRC1_DST4,
   ALIGN_SRC1_DST2,
   NUM_ALIGNMENTS,
};

struct align_info_t {
   const char *string;
   unsigned src_offset;
   unsigned dst_offset;
};

#define ALIGN_BOTH(value)        [ALIGN_##value] = {"both="#value, value, value}
#define ALIGN_SRC(src)           [ALIGN_SRC##src] = {"src="#src, src, 0}
#define ALIGN_DST(dst)           [ALIGN_DST##dst] = {"dst="#dst, 0, dst}
#define ALIGN_SRC_DST(src, dst)  [ALIGN_SRC##src##_DST##dst] = {"src="#src".dst="#dst, src, dst}

static const struct align_info_t align_info[] = {
   [ALIGN_MAX] = {"maxalign", 0, 0},
   ALIGN_BOTH(256),
   ALIGN_BOTH(128),
   ALIGN_BOTH(64),
   ALIGN_BOTH(4),
   ALIGN_BOTH(2),
   ALIGN_BOTH(1),
   ALIGN_SRC(256),
   ALIGN_SRC(128),
   ALIGN_SRC(64),
   ALIGN_SRC(4),
   ALIGN_SRC(2),
   ALIGN_SRC(1),
   ALIGN_DST(256),
   ALIGN_DST(128),
   ALIGN_DST(64),
   ALIGN_DST(4),
   ALIGN_DST(2),
   ALIGN_DST(1),
   ALIGN_SRC_DST(4, 2),
   ALIGN_SRC_DST(4, 1),
   ALIGN_SRC_DST(2, 4),
   ALIGN_SRC_DST(2, 1),
   ALIGN_SRC_DST(1, 4),
   ALIGN_SRC_DST(1, 2),
};

enum test_stage {
   COUNT_TESTS,
   RUN,
   REPORT,
};

static unsigned
next_size(unsigned size)
{
   int order = logbase2(size) - 3;
   assert(order >= 2);

   return ALIGN_POT((unsigned)(size * SIZE_STEP_MUL), 1 << order);
}

static void
run(api_context *ctx, const char *test_name, enum test_stage stage,
    api_query_pool *timestamps, unsigned *num_tests, api_queue_type queue)
{
   if (stage == REPORT) {
      printf("%-53s", "Allocation size");
      for (unsigned size = MIN_SIZE; size <= MAX_SIZE; size = next_size(size)) {
         if (size >= 4 * 1024 * 1024)
            printf(",%6uMB", size / (1024 * 1024));
         else if (size >= 4 * 1024)
            printf(",%6uKB", size / 1024);
         else
            printf(", %6uB", size);
      }
      printf("\n");
   }

   /* Create buffers. */
   /* We allocate enough memory and cycle through the whole range to prevent caching. */
   unsigned buf_size = stage == RUN ? 2 * MAX_SIZE + 256 : 1;
   api_buffer *devmem0 = ctx->create_buffer(ctx, buf_size, api_heap_device, 0);
   api_buffer *devmem1 = ctx->create_buffer(ctx, buf_size, api_heap_device, 0);
   api_buffer *hostmem = ctx->create_buffer(ctx, buf_size, api_heap_host_uncached, 0);

   unsigned num_visited_tests = 0;

   /* Run tests. */
   for (unsigned test_flavor = 0; test_flavor < NUM_TESTS; test_flavor++) {
      bool is_copy = test_flavor >= TEST_COPY_DEVMEM_TO_DEVMEM;
      api_buffer *dst = test_flavor == TEST_FILL_DEVMEM ||
                        test_flavor == TEST_COPY_DEVMEM_TO_DEVMEM ||
                        test_flavor == TEST_COPY_HOSTMEM_TO_DEVMEM ? devmem0 :
                        test_flavor == TEST_FILL_HOSTMEM ||
                        test_flavor == TEST_COPY_DEVMEM_TO_HOSTMEM ? hostmem : NULL;
      api_buffer *src = test_flavor == TEST_COPY_DEVMEM_TO_DEVMEM ||
                        test_flavor == TEST_COPY_DEVMEM_TO_HOSTMEM ? devmem1 :
                        test_flavor == TEST_COPY_HOSTMEM_TO_DEVMEM ? hostmem : NULL;
      assert(dst);
      assert(!src || src != dst);
      bool uses_hostmem = dst->heap != api_heap_device || (src && src->heap != api_heap_device);

      if (!ctx->has_heap[api_heap_host_uncached] && (dst == hostmem || src == hostmem))
         continue;

      for (unsigned cached = 0; cached < 2; cached ++) {
         unsigned cycled_offset_base = 0;

         for (unsigned align = 0; align < NUM_ALIGNMENTS; align++) {
            unsigned test_src_offset = align_info[align].src_offset;
            unsigned test_dst_offset = align_info[align].dst_offset;

            /* Don't be unaligned by some number from 0 for <= 2 byte alignment. Shift the offset by 4. */
            if (test_src_offset && test_src_offset < 4)
               test_src_offset += 4;
            if (test_dst_offset && test_dst_offset < 4)
               test_dst_offset += 4;

            if (!is_copy && (test_src_offset != 0 || test_dst_offset % 4))
               continue;

            if (stage == REPORT) {
               char name[1024];

               snprintf(name, sizeof(name), "%s.%s.%s.%s", test_name,
                        test_strings[test_flavor], cached ? "hit" : "miss",
                        align_info[align].string);
               printf("%-53s", name);
            }

            for (unsigned size = MIN_SIZE; size <= MAX_SIZE; size = next_size(size)) {
               /* Don't test large sizes with host memory because it can be too slow. */
               if (size > MAX_SIZE / HOSTMEM_TEST_REDUCTION && uses_hostmem) {
                  if (stage == REPORT)
                     printf(",%8s", "n/a");
                  continue;
               }

               if (stage == COUNT_TESTS)
                  (*num_tests)++;

               const unsigned execution_size = EXECUTION_SIZE / (uses_hostmem ? HOSTMEM_TEST_REDUCTION : 1);
               const unsigned num_runs = MAX2(MIN2(execution_size / size, MAX_RUNS), 1);
               const unsigned num_warmup_runs = MAX2(num_runs / 4, 1);

               if (stage == RUN) {
                  ctx->begin_cmdbuf(ctx, queue);

                  for (unsigned iter = 0; iter < num_warmup_runs + num_runs; iter++) {
                     if (iter == num_warmup_runs)
                        ctx->write_next_query_value(ctx, timestamps);

                     if ((cycled_offset_base + test_dst_offset + size > dst->size) ||
                         (is_copy && cycled_offset_base + test_src_offset + size > src->size))
                        cycled_offset_base = 0;

                     assert(cycled_offset_base + test_dst_offset + size <= dst->size);
                     assert(!is_copy || cycled_offset_base + test_src_offset + size <= src->size);
                     assert(cycled_offset_base % MAX_ALIGNMENT == 0);

                     uint64_t dst_offset = cycled_offset_base + test_dst_offset;

                     if (is_copy) {
                        uint64_t src_offset = cycled_offset_base + test_src_offset;

                        ctx->copy_buffer(ctx, dst, src, dst_offset, src_offset, size);
                        ctx->barrier_buffers(ctx, 2, (api_buffer*[2]){src, dst},
                                             (uint64_t[]){src_offset, size, dst_offset, size}, false);
                     } else {
                        ctx->clear_buffer(ctx, dst, dst_offset, size, 0x23456789);
                        ctx->barrier_buffers(ctx, 1, &dst, (uint64_t[]){dst_offset, size}, false);
                     }

                     if (!cached) {
                        /* Use a different portion of the buffers for each test, so that they don't just
                         * stay in the cache.
                         */
                        cycled_offset_base += size;
                        cycled_offset_base = ALIGN_POT(cycled_offset_base, MAX_ALIGNMENT);
                     }
                  }

                  ctx->write_next_query_value(ctx, timestamps);
                  ctx->end_cmdbuf_and_submit(ctx, 0, NULL, NULL);
               }

               if (stage == REPORT) {
                  /* When copying from DEVMEM to DEVMEM, we put 2x demand on DEVMEM bandwidth, and when
                   * copying between DEVMEM and HOSTMEM, we put only 1x demand on each, so only double
                   * the size for DEVMEM->DEVMEM copies to use the real DEVMEM bandwidth usage.
                   */
                  uint64_t num_bytes = (uint64_t)size * num_runs *
                                       (test_flavor == TEST_COPY_DEVMEM_TO_DEVMEM ? 2 : 1);
                  print_throughput_from_next_timestamps(ctx, timestamps, num_bytes, NULL, "%8.2f", "%8s", 30);
               }

               if (stage == RUN)
                  print_progress(*num_tests, &num_visited_tests, 20);
            }

            if (stage == REPORT)
               puts("");
         }
      }
   }
}

void
test_bufbw(api_context *ctx, const char *test_name)
{
   api_queue_type queue;

   if (ctx->options.compute)
      queue = api_queue_compute;
   else if (ctx->options.transfer)
      queue = api_queue_transfer;
   else
      queue = api_queue_gfx;

   if (!ctx->has_queue[queue])
      error("%s queue support is required.", queue_to_string(queue));

   printf("Using the %s queue.\n", queue_to_string(queue));

   unsigned num_tests = 0;
   run(ctx, test_name, COUNT_TESTS, NULL, &num_tests, queue);

   /* Create timestamp queries. */
   api_query_pool *timestamps =
      ctx->create_query_pool(ctx, num_tests * 2, api_query_timestamp);

   printf("Executing tests ...");
   run(ctx, test_name, RUN, timestamps, &num_tests, queue);
   puts("");

   ctx->get_query_results(ctx, timestamps);

   puts("Units: GB/s");
   run(ctx, test_name, REPORT, timestamps, &num_tests, queue);
}
